import Header from "@/components/Header";
import "../styles/globals.css";
import PromptInput from "@/components/PromptInput";

export const metadata = {
  title: "AI Image Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header />
        {/* Prompt Input */}
        <PromptInput />

        {children}
      </body>
    </html>
  );
}
